# .github/workflows/pre-commit.yml

name: Run Pre-commit Hooks

on:
    pull_request:
      branches:
        - '*'

jobs:
  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: macos-latest  # Use macOS for iOS projects

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install pre-commit hooks
        run: |
          pre-commit install

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
